name: "Configure AWS Region"
description: "Receives AWS Region and output it"
inputs:
  region:
    description: 'AWS Region to Deploy'
    required: true
    default: 'ap-south-1'
outputs:
  region: # id of output
    description: "AWS Region to deployed"